### ISSUE TITLE
"cannot create merkle proof" error

### ISSUE THREAD

**Issue by dmp1ce** [romanz/electrs#274] opened 2020-07-15 12:24 UTC
I am syncing on Testnet. I had some trasaction come in but then one of them started showing up as "Not verified" and the ElectRS server seemed to keep crashing. Here is the log for where the crash occurs.

I'm using v0.8.3.

```
2020-07-15T12:17:14.680+00:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.scripthash.subscribe\", \"id\": 40, \"params\": [\"xxxxxxxx\"]}\n")
2020-07-15T12:17:14.686+00:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.scripthash.subscribe\", \"id\": 41, \"params\": [\"xxxxxxxxxx\"]}\n")
2020-07-15T12:17:14.689+00:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.transaction.get_merkle\", \"id\": 42, \"params\": [\"xxxxxxxxxxxx\", 1780719]}\n")
2020-07-15T12:17:14.690+00:00 - WARN - rpc #42 blockchain.transaction.get_merkle [String("xxxxxxxxxx"), Number(1780719)] failed: Error: cannot create merkle proof
Caused by: missing txid xxxxxxxxxxxx

2020-07-15T12:17:15.241+00:00 - DEBUG - failed to send PeriodicUpdate to peer 4: sending on a full channel 
2020-07-15T12:17:15.243+00:00 - DEBUG - failed to send PeriodicUpdate to peer 7: sending on a full channel 
```

Also, my Electrum client keeps reconnecting, trying to get a balance but not being able to.

**Comment by Kixunil** [comment] 2020-07-15 15:13
Do you have pruning turned **off**?

**Comment by dmp1ce** [comment] 2020-07-15 15:21
I am not sure. Would that setting be in Electrs or Bitcoind?

**Comment by romanz** [comment] 2020-07-16 09:58
It's a bitcoind configuration - you can see its current value using:
```
bitcoin-cli getblockchaininfo | grep pruned
```

**Comment by romanz** [comment] 2020-07-16 10:06
@dmp1ce Would it be possible to share the transaction ID, in case the failure is reproducible?

**Comment by dmp1ce** [comment] 2020-07-16 12:35
Not pruned.

```
{
  "chain": "test",
  "blocks": 1780849,
  "headers": 1780849,
  "bestblockhash": "00000000e23fe4440c7c68f1537999641120c52bcc037ad482a7f03b84216e55",
  "difficulty": 1,
  "mediantime": 1594897118,
  "verificationprogress": 0.9999997263961092,
  "initialblockdownload": false,
  "chainwork": "0000000000000000000000000000000000000000000001acc378c111dae663f6",
  "size_on_disk": 27643165039,
  "pruned": false,
  "softforks": {
    "bip34": {
      "type": "buried",
      "active": true,
      "height": 21111
    },
    "bip66": {
      "type": "buried",
      "active": true,
      "height": 330776
    },
    "bip65": {
      "type": "buried",
      "active": true,
      "height": 581885
    },
    "csv": {
      "type": "buried",
      "active": true,
      "height": 770112
    },
    "segwit": {
      "type": "buried",
      "active": true,
      "height": 834624
    }
  },
  "warnings": "Warning: unknown new rules activated (versionbit 28)"
}
```

I think the chain might have experienced and some orphan blocks. I had mined a block and then I think it was forked off. I'm not sure if that could have caused the issue.

logs from electrs:
```
electrs_1  | 2020-07-16T12:33:39.667+00:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.scripthash.subscribe\", \"id\": 40, \"params\": [\"cc2dc0f3a8b381ebf12dc730f149706f733adb441fb192a8f9b4d951cfdfc67d\"]}\n")
electrs_1  | 2020-07-16T12:33:39.670+00:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.scripthash.subscribe\", \"id\": 41, \"params\": [\"485e299823fe1bdfdd311b9c2a2eda8c2591dfde9a24f76004817ff2b9f0fc26\"]}\n")
electrs_1  | 2020-07-16T12:33:39.678+00:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.scripthash.subscribe\", \"id\": 42, \"params\": [\"bb5cbfa2390bc8f3b1126145f41d870c0369c2e2826577436aa451f6f9b2fc6d\"]}\n")
electrs_1  | 2020-07-16T12:33:39.681+00:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.transaction.get_merkle\", \"id\": 43, \"params\": [\"8b0872ca7d825c57ae77107bbc6f0dd837eb600e02064f14d626650ae523a9b3\", 1780719]}\n")
electrs_1  | 2020-07-16T12:33:39.682+00:00 - WARN - rpc #43 blockchain.transaction.get_merkle [String("8b0872ca7d825c57ae77107bbc6f0dd837eb600e02064f14d626650ae523a9b3"), Number(1780719)] failed: Error: cannot create merkle proof
electrs_1  | Caused by: missing txid 8b0872ca7d825c57ae77107bbc6f0dd837eb600e02064f14d626650ae523a9b3
electrs_1  | 
electrs_1  | 2020-07-16T12:33:39.914+00:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.block.headers\", \"id\": 44, \"params\": [1780128, 722]}\n")
electrs_1  | 2020-07-16T12:33:40.355+00:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.scripthash.get_history\", \"id\": 45, \"params\": [\"a86c495370d32570041ea96ebfa1288446a0491d5f66e42202998348ee556541\"]}\n")
electrs_1  | 2020-07-16T12:33:40.442+00:00 - TRACE - RPC Done
electrs_1  | 2020-07-16T12:33:40.444+00:00 - DEBUG - [127.0.0.1:48552] shutting down connection
electrs_1  | 2020-07-16T12:33:40.447+00:00 - INFO - [127.0.0.1:48552] disconnected peer #153
electrs_1  | 2020-07-16T12:33:42.013+00:00 - INFO - [127.0.0.1:48556] connected peer #154
electrs_1  | 2020-07-16T12:33:42.089+00:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"server.version\", \"id\": 0, \"params\": [\"electrum/4.0.2\", \"1.4\"]}\n")
electrs_1  | 2020-07-16T12:33:42.823+00:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.headers.subscribe\", \"id\": 1}\n")
```

**Comment by romanz** [comment] 2020-07-17 08:29
Indeed, it seems that the `8b0872ca7d825c57ae77107bbc6f0dd837eb600e02064f14d626650ae523a9b3` transaction is not available any more in Testnet:
https://blockstream.info/testnet/tx/8b0872ca7d825c57ae77107bbc6f0dd837eb600e02064f14d626650ae523a9b3

**Comment by dmp1ce** [comment] 2020-07-17 13:28
Can ElectRS be modified tor eturn a response to Electrum that the transaction doesn't exist anymore instead of restarting/crashing?

Otherwise, how can I recover my server so that it reports correctly to Electrum? Should I delete the ElectRS cache an resync?

**Comment by Kixunil** [comment] 2020-07-18 14:47
Looks like it's [a TODO](https://github.com/romanz/electrs/blob/fac73dc1bf2d6644822e764ca68334b34f40d44f/src/rpc.rs#L329). However, I don't see any code in there causing crash, it just warns. Logs don't look like a crash either. Are you sure it crashes?

**Comment by dmp1ce** [comment] 2020-07-20 12:21
It probably isn't a crash but from the Electrum client it keeps disconnecting and reconnecting and then scanning all the transactions again.

**Comment by dmp1ce** [comment] 2020-07-21 02:06
Here is the error messages from electrum which I try to connect to my ElectRS. It looks like the error from ElectRS is not expected by Electrum. I'm not sure what the correct way to format the error messages would be.

Also, shouldn't ElectRS clear out invalid transactions if they are orphaned? I still get Electrum errors after creating a new wallet from the seed.

```
E/i | interface.[xxxxxxxxxxxxxx.onion:60002] | Exception in wrapper_func: <UntrustedServerReturnedError [DO NOT TRUST THIS MESSAGE] original_exception: ProtocolError(-32600, 'ill-formed response error object: cannot create merkle proof')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/electrum/network.py", line 837, in wrapper
    return await func(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/electrum/network.py", line 845, in get_merkle_for_transaction
    return await self.interface.get_merkle_for_transaction(tx_hash=tx_hash, tx_height=tx_height)
  File "/usr/lib/python3.8/site-packages/electrum/interface.py", line 882, in get_merkle_for_transaction
    res = await self.session.send_request('blockchain.transaction.get_merkle', [tx_hash, tx_height])
  File "/usr/lib/python3.8/site-packages/electrum/interface.py", line 164, in send_request
    response = await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/site-packages/aiorpcx/session.py", line 529, in send_request
    return await self._send_concurrent(message, future, 1)
  File "/usr/lib/python3.8/site-packages/aiorpcx/session.py", line 499, in _send_concurrent
    return await future
  File "/usr/lib/python3.8/site-packages/aiorpcx/jsonrpc.py", line 721, in receive_message
    item, request_id = self._protocol.message_to_item(message)
  File "/usr/lib/python3.8/site-packages/aiorpcx/jsonrpc.py", line 273, in message_to_item
    return cls._process_response(payload)
  File "/usr/lib/python3.8/site-packages/aiorpcx/jsonrpc.py", line 220, in _process_response
    raise cls._error(code, message, False, request_id)
aiorpcx.jsonrpc.ProtocolError: (-32600, 'ill-formed response error object: cannot create merkle proof')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/electrum/util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/electrum/interface.py", line 466, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/electrum/interface.py", line 490, in run
    await self.open_session(ssl_context)
  File "/usr/lib/python3.8/site-packages/electrum/interface.py", line 630, in open_session
    await group.spawn(self.monitor_connection)
  File "/usr/lib/python3.8/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/lib/python3.8/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/lib/python3.8/site-packages/electrum/verifier.py", line 63, in _start_tasks
    await group.spawn(self.main)
  File "/usr/lib/python3.8/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/lib/python3.8/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/lib/python3.8/site-packages/electrum/verifier.py", line 99, in _request_and_verify_single_proof
    merkle = await self.network.get_merkle_for_transaction(tx_hash, tx_height)
  File "/usr/lib/python3.8/site-packages/electrum/network.py", line 818, in make_reliable_wrapper
    raise success_fut.exception()
  File "/usr/lib/python3.8/site-packages/electrum/network.py", line 839, in wrapper
    raise UntrustedServerReturnedError(original_exception=e) from e
electrum.network.UntrustedServerReturnedError: The server returned an error.
E/i | interface.[xxxxxxxxxxxxxx.onion:60002] | Exception in wrapper_func: <UntrustedServerReturnedError [DO NOT TRUST THIS MESSAGE] original_exception: ProtocolError(-32600, 'ill-formed response error object: cannot create merkle proof')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/electrum/network.py", line 837, in wrapper
    return await func(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/electrum/network.py", line 845, in get_merkle_for_transaction
    return await self.interface.get_merkle_for_transaction(tx_hash=tx_hash, tx_height=tx_height)
  File "/usr/lib/python3.8/site-packages/electrum/interface.py", line 882, in get_merkle_for_transaction
    res = await self.session.send_request('blockchain.transaction.get_merkle', [tx_hash, tx_height])
  File "/usr/lib/python3.8/site-packages/electrum/interface.py", line 164, in send_request
    response = await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/site-packages/aiorpcx/session.py", line 529, in send_request
    return await self._send_concurrent(message, future, 1)
  File "/usr/lib/python3.8/site-packages/aiorpcx/session.py", line 499, in _send_concurrent
    return await future
  File "/usr/lib/python3.8/site-packages/aiorpcx/jsonrpc.py", line 721, in receive_message
    item, request_id = self._protocol.message_to_item(message)
  File "/usr/lib/python3.8/site-packages/aiorpcx/jsonrpc.py", line 273, in message_to_item
    return cls._process_response(payload)
  File "/usr/lib/python3.8/site-packages/aiorpcx/jsonrpc.py", line 220, in _process_response
    raise cls._error(code, message, False, request_id)
aiorpcx.jsonrpc.ProtocolError: (-32600, 'ill-formed response error object: cannot create merkle proof')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/electrum/util.py", line 1037, in wrapper
    return await func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/electrum/interface.py", line 466, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/electrum/interface.py", line 490, in run
    await self.open_session(ssl_context)
  File "/usr/lib/python3.8/site-packages/electrum/interface.py", line 630, in open_session
    await group.spawn(self.monitor_connection)
  File "/usr/lib/python3.8/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/lib/python3.8/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/lib/python3.8/site-packages/electrum/verifier.py", line 63, in _start_tasks
    await group.spawn(self.main)
  File "/usr/lib/python3.8/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/lib/python3.8/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/lib/python3.8/site-packages/electrum/verifier.py", line 99, in _request_and_verify_single_proof
    merkle = await self.network.get_merkle_for_transaction(tx_hash, tx_height)
  File "/usr/lib/python3.8/site-packages/electrum/network.py", line 818, in make_reliable_wrapper
    raise success_fut.exception()
  File "/usr/lib/python3.8/site-packages/electrum/network.py", line 839, in wrapper
    raise UntrustedServerReturnedError(original_exception=e) from e
electrum.network.UntrustedServerReturnedError: The server returned an error.
```

**Comment by Kixunil** [comment] 2020-07-21 20:05
I believe the log pretty much confirms that the above mentioned TODO needs to be resolved to fix it.

**Comment by dmp1ce** [comment] 2020-07-23 15:49
As a workaround, I backed up my `config`, then deleted the `config`, started electrum. The transactions then were detected correctly. I then closed electrum, copied my backup of `config` back to where it previously was. Started electrum again and then ElectRS didn't return any errors.

**Comment by romanz** [comment] 2021-10-03 12:15
Closing for now, please reopen if the issue is not resolved in the latest `master`.

**Closed by romanz** 2021-10-03 12:15 UTC
