### ISSUE TITLE
Server panics upon Electrum client connection

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#16] opened 2018-07-13 19:57 UTC
Following https://github.com/romanz/electrs/issues/9#issuecomment-404020135, the server panics with:
```
thread 'reader' panicked at 'failed to read a request: \
 Custom { kind: InvalidData, error: StringError("stream did not contain valid UTF-8") }', \
  libcore/result.rs:945:5

```

**Comment by romanz** [comment] 2018-07-13 19:58
@gabridome could you please attach the full log of the error (using https://asciinema.org if possible)?

**Comment by romanz** [comment] 2018-07-13 20:00
I'll also add a flag for logging Electrum client requests, for debugging this issue.

**Comment by romanz** [comment] 2018-07-14 07:11
Thanks!
From the error message, it seems that the bitcoind connection is closed, causing blocks' download to fail as well.

**Comment by romanz** [comment] 2018-07-14 08:38
I think that it is safe to restart the server in this case, so it would make progress.
Could you please run it again, now with RUST_BACKTRACE=1 (in case there will be more panics).

**Comment by romanz** [comment] 2018-07-14 09:39
P.S.
I've tested the server with the latest Electrum version (3.2.2, from https://github.com/spesmilo/electrum/commit/f8ee20322551575c3f969d4b00dfb3c441ac1b3f) and it seems to work correctly.
Do you still get the "stream did not contain valid UTF-8" error?

**Comment by romanz** [comment] 2018-07-14 13:18
P.S.
I'd also suggest using the latest version of `electrs`; since #15, the initial indexing should take <2h - so please try to run it over a new DB directory, using `--db-dir ./new-db`

**Comment by gabridome** [comment] 2018-07-15 05:33
here the relevant details of last crash:
````
2018-07-15T02:46:33.130+02:00 - TRACE - indexed "/home/bitcoin/.bitcoin/blocks/blk01314.dat": 1296111 rows
2018-07-15T02:46:42.980+02:00 - TRACE - indexed "/home/bitcoin/.bitcoin/blocks/blk01315.dat": 1303393 rows
2018-07-15T02:46:48.364+02:00 - DEBUG - no more blocks to index
2018-07-15T02:46:48.364+02:00 - TRACE - indexed "/home/bitcoin/.bitcoin/blocks/blk01316.dat": 1417299 rows
2018-07-15T02:46:52.997+02:00 - DEBUG - skipping block 0000000000000000000af3a3ab4a4f27989112869117b279f26c216a95753cae
2018-07-15T02:46:52.998+02:00 - DEBUG - skipping block 000000000000000000178159c09e4ae685789a3781532164c64c95b5c54e4ef5
2018-07-15T02:46:52.999+02:00 - DEBUG - skipping block 000000000000000000152010586d590290b50de430d34eddff2d1e3e378c63a3
2018-07-15T02:46:53.001+02:00 - DEBUG - skipping block 000000000000000000108023b38ce720d2519ff6baac4d8de8f994f4674e3e2f
2018-07-15T02:46:53.002+02:00 - DEBUG - skipping block 00000000000000000033c43a9dd05842eba2da7559cad11f1a6031709f82c91e
2018-07-15T02:46:53.004+02:00 - DEBUG - skipping block 000000000000000000341d06be33e8f61efd3f9b4d4b94aa279ba625932c6ff9
2018-07-15T02:46:53.006+02:00 - DEBUG - skipping block 0000000000000000002a7b8031f428df318fa569264aabba58f7ff9c75dd2451
2018-07-15T02:46:53.008+02:00 - DEBUG - skipping block 00000000000000000028a8d939fce369f57f34bb699720977ea97beb6c04d20d
2018-07-15T02:46:53.009+02:00 - DEBUG - skipping block 0000000000000000000491711949d918304c9ae31dc173b2c82f2dec619df0fa
2018-07-15T02:46:53.011+02:00 - DEBUG - skipping block 00000000000000000013c211dd6e6d94108e27c6bc19d7ddbfd0948a080b576c
2018-07-15T02:46:53.013+02:00 - DEBUG - skipping block 00000000000000000009c56000cafb0d96cc68f97e7b83554292bc32a57a6cb0
2018-07-15T02:46:53.013+02:00 - DEBUG - skipping block 0000000000000000003119187a7b815ef10f6847ec437a3875512f945a283bba
2018-07-15T02:46:53.016+02:00 - DEBUG - skipping block 0000000000000000000a8eea5c0fb56092606c6189ef56ea4d2ac1b98c2fe72f
2018-07-15T02:46:53.017+02:00 - DEBUG - skipping block 000000000000000000075aca039f2c691639db8a7f9b71b8aeda08badf98e2de
2018-07-15T02:46:53.019+02:00 - DEBUG - skipping block 0000000000000000002213d0fb9cb66240869d952f98843558894447562c9bab
2018-07-15T02:46:53.021+02:00 - DEBUG - skipping block 00000000000000000032e854553157a22c9fbacfbfb071864b93df63c2ccd409
2018-07-15T02:46:53.021+02:00 - DEBUG - skipping block 000000000000000000241d9895c1025be792a6904ee3478f7c1fa76059f2e8a0
2018-07-15T02:46:54.681+02:00 - DEBUG - no more blocks to index
2018-07-15T02:46:54.681+02:00 - TRACE - indexed "/home/bitcoin/.bitcoin/blocks/blk01317.dat": 982483 rows
2018-07-15T02:46:55.952+02:00 - DEBUG - last indexed block: best=0000000000000000001ee65a358378e88de81f3303c3ed8922923da76ac9528c height=531938 @ 2018-07-14T21:28:19Z
2018-07-15T02:46:56.147+02:00 - INFO - starting full compaction
2018-07-15T04:59:06.801+02:00 - INFO - finished full compaction
2018-07-15T05:00:51.041+02:00 - DEBUG - applying 531939 new headers from height 0
2018-07-15T05:00:51.604+02:00 - DEBUG - downloading new block headers (531939 already indexed) from 0000000000000000002c18161bd065cdf9aea4e20e200ee1d11b3d563bdcadb5
2018-07-15T05:00:51.606+02:00 - TRACE - downloaded 0000000000000000002c18161bd065cdf9aea4e20e200ee1d11b3d563bdcadb5 block header
2018-07-15T05:00:51.607+02:00 - TRACE - downloaded 0000000000000000002a00b22bc3001a5c17e2dfbd6dbe6c9a81635dc68b4d71 block header
2018-07-15T05:00:51.607+02:00 - TRACE - downloaded 00000000000000000018782ad6b3cd8d080a72b58e139344a4de9a5ff6797f74 block header
2018-07-15T05:00:51.608+02:00 - TRACE - downloaded 000000000000000000097874682de791bdecd8add33919da4be4b366b1424729 block header
2018-07-15T05:00:51.608+02:00 - TRACE - downloaded 000000000000000000273528f9fce9f2dab9ec572dc904be42062eca94cb5a43 block header
2018-07-15T05:00:51.609+02:00 - TRACE - downloaded 0000000000000000000f06f57b6a780210b7f8956716b437af40ad1392eab90e block header
2018-07-15T05:00:51.610+02:00 - TRACE - downloaded 00000000000000000019bdea6860b21f5acb1bd12b5d3d3d0bafd337629ec316 block header
2018-07-15T05:00:51.610+02:00 - TRACE - downloaded 0000000000000000000f2f2132d3bccfabbd11d5c42d04379842a46a5ca7633a block header
2018-07-15T05:00:51.610+02:00 - TRACE - downloaded 00000000000000000002236fdfdbbe473122bd5ddef892a747f0b3d50db1052f block header
2018-07-15T05:00:51.611+02:00 - TRACE - downloaded 000000000000000000241d9895c1025be792a6904ee3478f7c1fa76059f2e8a0 block header
2018-07-15T05:00:51.612+02:00 - TRACE - downloaded 00000000000000000032e854553157a22c9fbacfbfb071864b93df63c2ccd409 block header
2018-07-15T05:00:51.612+02:00 - TRACE - downloaded 0000000000000000002213d0fb9cb66240869d952f98843558894447562c9bab block header
2018-07-15T05:00:51.613+02:00 - TRACE - downloaded 000000000000000000075aca039f2c691639db8a7f9b71b8aeda08badf98e2de block header
2018-07-15T05:00:51.613+02:00 - TRACE - downloaded 0000000000000000000a8eea5c0fb56092606c6189ef56ea4d2ac1b98c2fe72f block header
2018-07-15T05:00:51.614+02:00 - TRACE - downloaded 0000000000000000003119187a7b815ef10f6847ec437a3875512f945a283bba block header
2018-07-15T05:00:51.614+02:00 - TRACE - downloaded 00000000000000000009c56000cafb0d96cc68f97e7b83554292bc32a57a6cb0 block header
2018-07-15T05:00:51.614+02:00 - TRACE - downloaded 00000000000000000013c211dd6e6d94108e27c6bc19d7ddbfd0948a080b576c block header
2018-07-15T05:00:51.615+02:00 - TRACE - downloaded 0000000000000000000491711949d918304c9ae31dc173b2c82f2dec619df0fa block header
2018-07-15T05:00:51.615+02:00 - TRACE - downloaded 00000000000000000028a8d939fce369f57f34bb699720977ea97beb6c04d20d block header
2018-07-15T05:00:51.615+02:00 - TRACE - downloaded 0000000000000000002a7b8031f428df318fa569264aabba58f7ff9c75dd2451 block header
2018-07-15T05:00:51.616+02:00 - TRACE - downloaded 000000000000000000341d06be33e8f61efd3f9b4d4b94aa279ba625932c6ff9 block header
2018-07-15T05:00:51.616+02:00 - TRACE - downloaded 00000000000000000033c43a9dd05842eba2da7559cad11f1a6031709f82c91e block header
2018-07-15T05:00:51.616+02:00 - TRACE - downloaded 000000000000000000108023b38ce720d2519ff6baac4d8de8f994f4674e3e2f block header
2018-07-15T05:00:51.617+02:00 - TRACE - downloaded 000000000000000000152010586d590290b50de430d34eddff2d1e3e378c63a3 block header
2018-07-15T05:00:51.617+02:00 - TRACE - downloaded 000000000000000000178159c09e4ae685789a3781532164c64c95b5c54e4ef5 block header
2018-07-15T05:00:51.617+02:00 - TRACE - downloaded 0000000000000000000af3a3ab4a4f27989112869117b279f26c216a95753cae block header
2018-07-15T05:00:51.618+02:00 - INFO - best=0000000000000000002c18161bd065cdf9aea4e20e200ee1d11b3d563bdcadb5 height=531964 @ 2018-07-15T02:40:00Z (26 left to index)
2018-07-15T05:00:59.503+02:00 - DEBUG - applying 26 new headers from height 531939
2018-07-15T05:00:59.534+02:00 - TRACE - closing DB
2018-07-15T05:01:00.224+02:00 - ERROR - server failed: Error: failed to update mempool from daemon
Caused by: RPC failed: {"method":"getrawmempool","params":[false]}
Caused by: disconnected from daemon
stack backtrace:
   0:     0x55a58500f96c - backtrace::backtrace::trace::hd402417859783b40
   1:     0x55a58500efc2 - backtrace::capture::Backtrace::new_unresolved::hce1354e135c2f28e
   2:     0x55a58500e897 - error_chain::backtrace::imp::InternalBacktrace::new::habdd565038f6f85c
   3:     0x55a58500ec04 - <error_chain::State as core::default::Default>::default::hee976682d00eb04c
   4:     0x55a584fe29d5 - <core::option::Option<T> as electrs::errors::ResultExt<T>>::chain_err::he86d5244c2fb9016
   5:     0x55a584f439f7 - electrs::daemon::Daemon::call_jsonrpc::he1590ae21e77a3d8
   6:     0x55a584f4452b - electrs::daemon::Daemon::request::h2a3f07a1273cf39c
   7:     0x55a584f46d77 - electrs::daemon::Daemon::getmempooltxids::h586de0322bbacc1c
   8:     0x55a584f8c592 - electrs::mempool::Tracker::update::h9ba4bdd928b3816f
   9:     0x55a584f5687b - electrs::query::Query::update_mempool::h5eb8efaaf290c970
  10:     0x55a584f3e696 - electrs::main::hb7893ebc8a38666e
  11:     0x55a584f398c2 - std::rt::lang_start::{{closure}}::h825937f5b6ee0646
  12:     0x55a585440902 - std::rt::lang_start_internal::{{closure}}::h342eaeec3a520255
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h8b090b6144a018fb
                        at libstd/panicking.rs:310
  13:     0x55a58545e869 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  14:     0x55a585447df5 - std::panicking::try::h11349d7f0dce3b3c
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::hfbb0f172d1ed4df2
                        at libstd/panic.rs:374
                         - std::rt::lang_start_internal::h6c73689767a9401e
                        at libstd/rt.rs:58
  15:     0x55a584f3ede3 - main
  16:     0x7fb3828e882f - __libc_start_main
  17:     0x55a584f37888 - _start
  18:                0x0 - <unknown>

**Comment by romanz** [comment] 2018-07-15 06:32
The 2nd panic is actually a bug, so thanks a lot for helping me to find and fix it :)

**Comment by romanz** [comment] 2018-07-15 06:51
Regarding the 1st panic - it seems that JSONRPC connection was been disconnected (so the mempool polling failed), but I'm still not sure why this happens...
Could you look at the `~/.bitcoin/debug.log` to see if there are any errors that may be related to this issue?

P.S.
You can run `bitcoind -debug=rpc -debug=http` to get more RPC/HTTP specific logging...

**Comment by romanz** [comment] 2018-07-15 06:53
I've opened a new bug for handling graceful JSON RPC disconnections -> #18.

**Comment by romanz** [comment] 2018-07-15 19:41
> I had c-lightning, lnd and electrs insisting on the same rpc api of my bitcoind. Is it possible that many connections/request makes it shut down or similar behaviours?

Good suggestion - this should be solved by #19

**Comment by gabridome** [comment] 2018-07-15 20:15
The program was running ok but when I fired up electrum it crashed.
here  the relevant log from the current crash:

````
2018-07-15T22:04:07.339+02:00 - WARN - no mempool entry 21fc1c8585e33d0113c5aa63233945174b110aa3422e87607ce0666346ce1803: missing fees section
2018-07-15T22:04:07.340+02:00 - INFO - RPC server running on 127.0.0.1:50001
2018-07-15T22:04:10.898+02:00 - INFO - [127.0.0.1:50460] connected peer
thread 'reader' panicked at 'failed to read a request: Custom { kind: InvalidData, error: StringError("stream did not contain valid UTF-8") }', libcore/result.rs:945:5
stack backtrace:
   0:     0x563218fe6e1e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::he2ad84a733ff5a63
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x563218fed256 - std::sys_common::backtrace::print::hf6fb23a1794250a5
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x563218fd626b - std::panicking::default_hook::{{closure}}::ha69c5f3cb0459cff
                               at libstd/panicking.rs:211
   3:     0x563218fd5f43 - std::panicking::default_hook::hf08727ddbbbad4bb
                               at libstd/panicking.rs:227
   4:     0x563218fd688e - std::panicking::rust_panic_with_hook::hd6baf0cfc62bef0f
                               at libstd/panicking.rs:463
   5:     0x563218fd642c - std::panicking::begin_panic_fmt::h067a7944e7e0f96e
                               at libstd/panicking.rs:350
   6:     0x563218fd63f1 - rust_begin_unwind
                               at libstd/panicking.rs:328
   7:     0x56321902e592 - core::panicking::panic_fmt::h61b193aee9efb823
                               at libcore/panicking.rs:71
   8:     0x563218b3bf28 - core::result::unwrap_failed::hfae190ddb24b527f
   9:     0x563218b4d025 - electrs::rpc::Connection::handle_requests::h3407ccb403d2f267
  10:     0x563218b5fc78 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0497046b7d59a1a3
  11:     0x563218af7134 - std::panicking::try::do_call::h6d426ba7f081619f
  12:     0x563218ff42d9 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:105
  13:     0x563218b94c74 - <F as alloc::boxed::FnBox<A>>::call_box::h8c7e53b6f46d56cc
  14:     0x563218fe8cca - std::sys_common::thread::start_thread::hd31f5c5fa3e47024
                               at /checkout/src/liballoc/boxed.rs:648
                               at libstd/sys_common/thread.rs:24
  15:     0x563218fd6e25 - std::sys::unix::thread::Thread::new::thread_start::hb3e7825324ee0f62
                               at libstd/sys/unix/thread.rs:90
  16:     0x7f23d163c6b9 - start_thread
  17:     0x7f23d115c41c - clone
  18:                0x0 - <unknown>
`````
No relevant logs from bitcoind:

````
2018-07-15 20:04:07 Received a POST request for / from 127.0.0.1:40096
2018-07-15 20:04:07 ThreadRPCServer method=getmempoolentry
2018-07-15 20:04:07 Received a POST request for / from 127.0.0.1:40096
2018-07-15 20:04:12 Received a POST request for / from 127.0.0.1:40096
2018-07-15 20:04:12 ThreadRPCServer method=getbestblockhash
2018-07-15 20:04:12 Received a POST request for / from 127.0.0.1:40096
2018-07-15 20:04:12 ThreadRPCServer method=getrawmempool
2018-07-15 20:04:12 Received a POST request for / from 127.0.0.1:40096
2018-07-15 20:04:12 ThreadRPCServer method=getmempoolentry
2018-07-15 20:04:12 Received a POST request for / from 127.0.0.1:40096
`````

**Comment by gabridome** [comment] 2018-07-15 20:19
>Good suggestion - this should be solved by #19 :)

In which way? should I try to configure the service on a different port or IP?

**Comment by romanz** [comment] 2018-07-15 20:35
> In which way? should I try to configure the service on a different port or IP?

You can now configure Electrum RPC server address & port using `--electrum-rpc-addr 127.0.0.1:54321`.

**Comment by romanz** [comment] 2018-07-15 20:42
Regarding the "stream did not contain valid UTF-8" panic:
It seems that Electrum client is sending invalid data to the wallet...

You can test that the server works correctly by using `netcat`:
```bash
$ echo '{"id":0, "method": "server.version", "params": []}' | netcat localhost 50001
{"id":0,"jsonrpc":"2.0","result":["RustElectrum 0.1.0","1.2"]}
```
Does the above snippet work for you?

**Comment by gabridome** [comment] 2018-07-15 22:20
yes it does. It seems to work as expecteted.
````
~$ echo '{"id":0, "method": "server.version", "params": []}' | netcat localhost 50001
{"id":0,"jsonrpc":"2.0","result":["RustElectrum 0.1.0","1.2"]}
````
I connect to the server through an ssh tunnel: 
```
ssh bitcoin@myremoteelectrumserver -L 50001:localhost:50001
````
But still the electrum client show no connection (red light in the network signal).

**Comment by gabridome** [comment] 2018-07-15 22:53
After having changed the port. It works pretty much perfectly!!!

Thank you so much! and thanks to @greenaddress too for the new PR.

**Comment by romanz** [comment] 2018-07-16 04:48
You're welcome, thank you for the testing and the debugging :)

**Closed** 2018-07-16 04:48 UTC
Labels: bug

**Comment by gabridome** [comment] 2018-07-17 15:53
I don't know if opening an other issue because the problem seems quite the same.
After hours it worked perfectly, I launched electrum on the port 54321.

````
2018-07-17T17:44:30.080+02:00 - TRACE - 3845 transactions in mempool (+7)
2018-07-17T17:44:35.159+02:00 - TRACE - 3859 transactions in mempool (+14)
2018-07-17T17:44:40.287+02:00 - TRACE - 3875 transactions in mempool (+16)
2018-07-17T17:44:40.349+02:00 - INFO - [127.0.0.1:54886] connected peer
thread 'reader' panicked at 'failed to read a request: Custom { kind: InvalidData, error: StringError("stream did not contain valid UTF-8") }', libcore/result.rs:945:5
stack backtrace:
   0:     0x557c4e0b478e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::he2ad84a733ff5a63
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x557c4e0babc6 - std::sys_common::backtrace::print::hf6fb23a1794250a5
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x557c4e0a3bdb - std::panicking::default_hook::{{closure}}::ha69c5f3cb0459cff
                               at libstd/panicking.rs:211
   3:     0x557c4e0a38b3 - std::panicking::default_hook::hf08727ddbbbad4bb
                               at libstd/panicking.rs:227
   4:     0x557c4e0a41fe - std::panicking::rust_panic_with_hook::hd6baf0cfc62bef0f
                               at libstd/panicking.rs:463
   5:     0x557c4e0a3d9c - std::panicking::begin_panic_fmt::h067a7944e7e0f96e
                               at libstd/panicking.rs:350
   6:     0x557c4e0a3d61 - rust_begin_unwind
                               at libstd/panicking.rs:328
   7:     0x557c4e0fbf02 - core::panicking::panic_fmt::h61b193aee9efb823
                               at libcore/panicking.rs:71
   8:     0x557c4dc028a8 - core::result::unwrap_failed::hfae190ddb24b527f
   9:     0x557c4dc13365 - electrs::rpc::Connection::handle_requests::h3407ccb403d2f267
  10:     0x557c4dc2f3a8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0497046b7d59a1a3
  11:     0x557c4dbbc944 - std::panicking::try::do_call::h6d426ba7f081619f
  12:     0x557c4e0c1c49 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:105
  13:     0x557c4dc58cf4 - <F as alloc::boxed::FnBox<A>>::call_box::h8c7e53b6f46d56cc
  14:     0x557c4e0b663a - std::sys_common::thread::start_thread::hd31f5c5fa3e47024
                               at /checkout/src/liballoc/boxed.rs:648
                               at libstd/sys_common/thread.rs:24
  15:     0x557c4e0a4795 - std::sys::unix::thread::Thread::new::thread_start::hb3e7825324ee0f62
                               at libstd/sys/unix/thread.rs:90
  16:     0x7ff397c5e6b9 - start_thread
  17:     0x7ff39777e41c - clone
  18:                0x0 - <unknown>
2018-07-17T17:44:45.375+02:00 - TRACE - 3888 transactions in mempool (+13)
````
