### ISSUE TITLE
Can't build with rust 1.40.0

### ISSUE THREAD

**Issue by sangaman** [romanz/electrs#207] opened 2019-12-20 14:34 UTC
Building with rust 1.39.0 works fine. 1.40 gets the error below. This is on 32 bit armv7l hardware.

```
   Compiling librocksdb-sys v5.18.3
error: failed to run custom build command for `librocksdb-sys v5.18.3`

Caused by:
  process didn't exit successfully: `/home/bitcoin/electrs/target/release/build/librocksdb-sys-e908501be0012fa4/build-script-build` (exit code: 1)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/
NUM_JOBS = Some("8")
TARGET = Some("armv7-unknown-linux-gnueabihf")
OPT_LEVEL = Some("3")
HOST = Some("armv7-unknown-linux-gnueabihf")
CXX_armv7-unknown-linux-gnueabihf = None
CXX_armv7_unknown_linux_gnueabihf = None
HOST_CXX = None
CXX = None
CXXFLAGS_armv7-unknown-linux-gnueabihf = None
CXXFLAGS_armv7_unknown_linux_gnueabihf = None
HOST_CXXFLAGS = None
CXXFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = None

...

error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.7.0/fused-src/" "-I" "snappy/" "-I" "lz4/lib/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "zlib/" "-I" "bzip2/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DLZ4=1" "-DZSTD=1" "-DZLIB=1" "-DBZIP2=1" "-DNDEBUG=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/home/bitcoin/electrs/target/release/build/librocksdb-sys-3d51c0756006fa16/out/rocksdb/utilities/transactions/pessimistic_transaction_db.o" "-c" "rocksdb/utilities/transactions/pessimistic_transaction_db.cc" with args "c++" did not execute successfully (status code exit code: 1).
```

**Comment by 3ntranced** [comment] 2020-01-21 16:05
I am having the same build error on raspibolt right now

**Comment by 3ntranced** [comment] 2020-01-23 01:02
I was getting this problem because I missed the following line from the tutorial:
sudo apt install clang cmake

**Comment by romanz** [comment] 2020-01-27 20:35
Thanks for opening this issue, and sorry for the delayed response.
Would it be possible to reproduce this issue only for `rust-rocksdb` crate on ARM?

Also https://github.com/romanz/electrs/issues/201 :)

**Comment by sangaman** [comment] 2020-01-27 21:26
> Would it be possible to reproduce this issue only for rust-rocksdb crate on ARM?

How would I go about doing that? Sorry but I'm not that familiar with rust/cargo.

**Comment by romanz** [comment] 2020-01-30 19:00
You can clone https://github.com/rust-rocksdb/rust-rocksdb and run `cargo test` on it:
```
$ git clone https://github.com/rust-rocksdb/rust-rocksdb
$ cd rust-rocksdb
$ cargo test
```

**Comment by sangaman** [comment] 2020-01-30 22:54
> You can clone [rust-rocksdb/rust-rocksdb](https://github.com/rust-rocksdb/rust-rocksdb) and run `cargo test` on it:

**Comment by sangaman** [comment] 2020-01-31 03:47
I was just able to build electrs with 1.41.0 - if it was just a passing issue then maybe this can be closed?

**Comment by romanz** [comment] 2020-01-31 04:59
Sounds good, closing.

**Closed** 2020-01-31 04:59 UTC

**Comment by Stadicus** [comment] 2020-02-01 20:44
FWIW, I can confirm that building with Rust 1.41 works like a charm on the Raspberry Pi 4 (Raspbian Buster, ARMv7)

**Comment by sangaman** [comment] 2020-12-15 17:12
Looks like this issue is back... same setup as before with cargo 1.41.0, but now it won't build v5.15.5 using the latest from master.

```
   Compiling librocksdb-sys v5.18.5
error: failed to run custom build command for `librocksdb-sys v5.18.5`

Caused by:
  process didn't exit successfully: `/home/bitcoin/electrs/target/release/build/librocksdb-sys-bf582e2f480abbad/build-script-build` (exit code: 1)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
TARGET = Some("armv7-unknown-linux-gnueabihf")
OPT_LEVEL = Some("3")
HOST = Some("armv7-unknown-linux-gnueabihf")
CXX_armv7-unknown-linux-gnueabihf = None
CXX_armv7_unknown_linux_gnueabihf = None
HOST_CXX = None
CXX = None
CXXFLAGS_armv7-unknown-linux-gnueabihf = None
CXXFLAGS_armv7_unknown_linux_gnueabihf = None
HOST_CXXFLAGS = None
CXXFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = None
```

@Stadicus Can you see if you get the same issue?

**Comment by Stadicus** [comment] 2020-12-15 17:27
I just compiled Electrs a few days ago on a Raspberry Pi 4 using Rust 1.48.0 (see https://github.com/Stadicus/RaspiBolt/pull/673/commits/4a59a8e541f4cb34c67f2cb4289385cd54271455).

Not sure if that information helps. Is there a reason to stay on Rust 1.41?

**Comment by romanz** [comment] 2020-12-15 18:29
We are supporting Rust 1.41 since it the version installed on stable Debian:
https://packages.debian.org/stable/rustc

**Comment by romanz** [comment] 2020-12-15 18:32
> Looks like this issue is back... same setup as before with cargo 1.41.0, but now it won't build v5.15.5 using the latest from master.

Maybe you can try to build it with RocksDB being dynamically linked:
https://github.com/romanz/electrs/blob/master/doc/usage.md#dynamic-linking

**Comment by sangaman** [comment] 2020-12-16 12:49
> Maybe you can try to build it with RocksDB being dynamically linked:
> https://github.com/romanz/electrs/blob/master/doc/usage.md#dynamic-linking

I wasn't able to find any binaries for arm7 on ubuntu for `librocksdb-dev` so I couldn't figure out a way to get dynamic linking to work. But moving to 1.48.0 resolved the issue for me again... I guess some dependencies are losing compatibility with older rust versions?

**Comment by Kixunil** [comment] 2020-12-16 13:43
I actually attempted to cross compile rocksdb for arm7 a few weeks ago and failed. To me it looks like Rocksdb is not well supported on 32 bit OSes (Raspbian is 32 bit OS even if it, runs on 64 bit Rpi4). I did succeed at cross-compiling `electrs` for arm64 using dynamic linking.

If you have Pi4, I'd suggest considering moving to 64-bit OS (Debian, not Raspbian, I know it has disadvantages :( ). If you're in the mood to play with it you can also try out experimental version of [my repository](https://deb.ln-ask.me) which contains arm64 packages of various Bitcoin stuff including `electrs`. LMK if you're interested, setting up experimental version is purposely not well documented to discourage random people from using it.

FWIW, this should have nothing to do with Rust version. IDK why it appears as if it has.

**Comment by sangaman** [comment] 2020-12-17 14:14
> FWIW, this should have nothing to do with Rust version. IDK why it appears as if it has.

Do you think it's just coincidence? I tried building several times on 1.41 and it failed every time, then it worked the first time on 1.48.

I'm thinking about switching to a raspi4 with 8GB ram running 64 bit raspbian, so if/when I do I'll check out your repository. Thanks.

**Comment by Kixunil** [comment] 2020-12-17 15:01
That's very strange, the reason I believe it should be unrelated is that the **C** compiler appears to be failing during the build of rocksdb and Rust version should not affect it. This would need deeper analysis to tell for sure.

The main reason to use older version of Rust is that it's packaged in Debian repository and thus can be installed more safely. To my knowledge, rustup doesn't check signatures.

**Comment by Stadicus** [comment] 2020-12-17 15:14
> To my knowledge, rustup doesn't check signatures

In my guide, I install Rust manually, including signatures check:
https://stadicus.github.io/RaspiBolt/raspibolt_50_electrs.html#install-dependencies

**Comment by Kixunil** [comment] 2020-12-18 09:00
I mean, you're checking signature of Rustup, but Rustup doesn't check the signatures of downloaded components. Didn't verify this yet.

**Comment by Stadicus** [comment] 2020-12-18 09:05
> I mean, you're checking signature of Rustup, but Rustup doesn't check the signatures of downloaded components. Didn't verify this yet.

The archive (https://static.rust-lang.org/dist/rust-1.48.0-armv7-unknown-linux-gnueabihf.tar.gz) that is downloaded is 200 MB and IIUC it is simply installed locally. I'm not aware that there are additional components that are downloaded. But I might be wrong and I guess this discussion is a bit off-topic... :)

**Comment by Kixunil** [comment] 2020-12-18 09:19
Oh, sorry, I thought that guide downloaded Rustup, but it downloads Rust itself then. That's good! Would be nice to have the key verified from independent source and signed too.

Also we had an issue recently that someone installed Rust using your guide on x86_64, which broke the system. Perhaps an explicit warning that the guide will only work on RPi would be useful?

**Comment by Stadicus** [comment] 2020-12-22 08:57
> Also we had an issue recently that someone installed Rust using your guide on x86_64, which broke the system. Perhaps an explicit warning that the guide will only work on RPi would be useful?

Thanks for this hint, I added a warning: https://github.com/Stadicus/RaspiBolt/pull/682

-- off-topic out :)

**Comment by xanoni** [comment] 2021-07-16 10:01
Failing with standard Rust on Raspbian 32bit. Will need to manually upgrade Rust I guess.

```bash
$ sudo apt show rustc
Package: rustc
Version: 1.41.1+dfsg1-1~deb10u1+rpi1
[...]
```

Really long error that probably only makes sense to someone who knows more Rust.... but here's part of it:

```bash
error: linking with `cc` failed: exit code: 1
 313   |
 314   = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-L" "/usr/lib/rustlib/arm-unknown-linux-gnueabihf/lib" "/home/x/build-x/electrs/target/release/deps/electrs-70f3c9724b34fe26.electrs.cuwu3nr3-cgu.8.rcgu.o" "-o" "/home/x/build-x/electr     s/target/release/deps/electrs-70f3c9724b34fe26" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/x/build-x/electrs/target/release/deps" "-L" "/home/x/build-x/electrs/target/release/build/secp256k1     -sys-58b242fd4d82ba35/out" "-L" "/home/x/build-x/electrs/target/release/build/librocksdb-sys-cacf052246b6660a/out" "-L" "/home/x/build-x/electrs/target/release/build/librocksdb-sys-cacf052246b6660a/out" "-L" "/home/x/build-x/electrs/t     arget/release/build/librocksdb-sys-cacf052246b6660a/out" "-L" "/home/x/build-x/electrs/target/release/build/librocksdb-sys-cacf052246b6660a/out" "-L" "/home/x/build-x/electrs/target/release/build/librocksdb-sys-cacf052246b6660a/out" "-L" "     /home/x/build-x/electrs/target/release/build/librocksdb-sys-cacf052246b6660a/out" "-L" "/usr/lib/rustlib/arm-unknown-linux-gnueabihf/lib" "-Wl,-Bstatic" "/tmp/rustcciXb8Z/liblibrocksdb_sys-5d47561a2d7ab3d7.rlib" "/tmp/rustcciXb8Z/libsecp256k1_s     ys-7926396842a8961e.rlib" "-Wl,--start-group" "/tmp/rustcciXb8Z/libbacktrace_sys-e532c0caf96228eb.rlib" "-Wl,--end-group" "/usr/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libcompiler_builtins-d7d0d69bd6736485.rlib" "-Wl,-Bdynamic" "-lstdc++" "-luti     l" "-ldl" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
 315   = note: /usr/bin/ld: /tmp/rustcciXb8Z/liblibrocksdb_sys-5d47561a2d7ab3d7.rlib(db_impl_write.o): in function `rocksdb::DBImpl::WriteToWAL(rocksdb::WriteBatch const&, rocksdb::log::Writer*, unsigned long long*, unsigned long long*)':
 316           db_impl_write.cc:(.text._ZN7rocksdb6DBImpl10WriteToWALERKNS_10WriteBatchEPNS_3log6WriterEPyS7_+0x88): undefined reference to `__atomic_fetch_add_8'
 317           /usr/bin/ld: /tmp/rustcciXb8Z/liblibrocksdb_sys-5d47561a2d7ab3d7.rlib(db_impl_write.o): in function `rocksdb::DBImpl::AssignAtomicFlushSeq(rocksdb::autovector<rocksdb::ColumnFamilyData*, 8u> const&)':
 318           db_impl_write.cc:(.text._ZN7rocksdb6DBImpl20AssignAtomicFlushSeqERKNS_10autovectorIPNS_16ColumnFamilyDataELj8EEE+0x14): undefined reference to `__atomic_load_8'
 319           /usr/bin/ld: /tmp/rustcciXb8Z/liblibrocksdb_sys-5d47561a2d7ab3d7.rlib(db_impl_write.o): in function `rocksdb::DBImpl::DelayWrite(unsigned long long, rocksdb::WriteOptions const&)':
 320           db_impl_write.cc:(.text._ZN7rocksdb6DBImpl10DelayWriteEyRKNS_12WriteOptionsE+0x654): undefined reference to `__atomic_load_8'
 321           /usr/bin/ld: db_impl_write.cc:(.text._ZN7rocksdb6DBImpl10DelayWriteEyRKNS_12WriteOptionsE+0x66c): undefined reference to `__atomic_store_8'
 322           /usr/bin/ld: /tmp/rustcciXb8Z/liblibrocksdb_sys-5d47561a2d7ab3d7.rlib(db_impl_write.o): in function `rocksdb::DBImpl::SelectColumnFamiliesForAtomicFlush(rocksdb::autovector<rocksdb::ColumnFamilyData*, 8u>*)':
 323           db_impl_write.cc:(.text._ZN7rocksdb6DBImpl34SelectColumnFamiliesForAtomicFlushEPNS_10autovectorIPNS_16ColumnFamilyDataELj8EEE+0xa0): undefined reference to `__atomic_load_8'
 324           /usr/bin/ld: /tmp/rustcciXb8Z/liblibrocksdb_sys-5d47561a2d7ab3d7.rlib(db_impl_write.o): in function `rocksdb::DBImpl::WriteToWAL(rocksdb::WriteThread::WriteGroup const&, rocksdb::log::Writer*, unsigned long long*, bool, bool, unsigned long      long)':
```


Also tried this:

```bash
$ git clone https://github.com/rust-rocksdb/rust-rocksdb
$ cd rust-rocksdb
$ cargo test

[...]
   Compiling rand_chacha v0.3.1
   Compiling rand v0.8.4
   Compiling tempfile v3.2.0
   Compiling librocksdb-sys v6.20.3 (/home/x/build-x/rust-rocksdb/librocksdb-sys)
error[E0658]: use of unstable library feature 'matches_macro'
   --> librocksdb-sys/build.rs:169:18
    |
169 |                 !matches!(
    |                  ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `librocksdb-sys`.
warning: build failed, waiting for other jobs to finish...
    Building [=======================================>                 ] 64/89: serde_derive
error: build failed
```

**Comment by romanz** [comment] 2021-07-16 12:27
Please try building electrs with https://github.com/romanz/electrs/issues/403#issuecomment-845351578:
```
$ RUSTFLAGS="-C link-args=-latomic" cargo build --release --locked
```

**Comment by xanoni** [comment] 2021-07-17 16:42
> Please try building electrs with [#403 (comment)](https://github.com/romanz/electrs/issues/403#issuecomment-845351578):
> 
> ```
> $ RUSTFLAGS="-C link-args=-latomic" cargo build --release --locked
> ```

SUCCESS. Thank you, sir.
