### ISSUE TITLE
Bug: getmempoolentry RPC error

### ISSUE THREAD

**Issue by ascisco** [romanz/electrs#364] opened 2021-02-08 21:50 UTC
Ive been using Electrum + electrs as a PoS for a online business of mine so I get a lot of txs though it. 
For some reason when I load electrum it no longer syncs to my electrs server.

When I open the electrs logs it shows a long list of the following error `DEBUG - no mempool entry 8322da89e0fe37ee108d74c0f6a0d650b92540793f4ca380065cafda12fd4202: getmempoolentry RPC error: {"code":-5,"message":"Transaction not in mempool"}`

It shows a bunch of errors like this with different TXIDs but none of the IDs seem to be valid when entered into a block explorer. 

Im running electrs through the latest Umbrel 0.3.2 release.

**Comment by Kixunil** [comment] 2021-02-09 10:37
This could be a known issue that will hopefully be fixed eventually. (I'm working on it but it will take some time.)

However since you use Umbrel which is an early alpha software it could be caused by it. Any idea @lukechilds?

**Comment by ascisco** [comment] 2021-02-19 21:02
I was in contact with another electrs user and they faced the same problem. They said it arose with wallets with a lot of transaction history.

**Comment by lukechilds** [comment] 2021-02-20 07:41
I've seen this error before both when using Umbrel and using electrs outside of Umbrel so I don't think it's Umbrel related.

I had assumed it was when you make a transaction with Electrum that won't confirm for a while, then close Electrum, then in the meantime it's discarded from your node's mempool, then you open Electrum and it tries to request the transaction from your node which no longer has it.

That's just an assumption but it seemed to make sense to me. If that's it, it's not anything to worry about since it should show up again once it's confirmed. Alternatively electrs could keep a copy of all broadcast transactions internally to ensure it can respond to lookup requests until the transaction gets confirmed, even if Core discards it.

**Comment by ascisco** [comment] 2021-02-20 09:51
> I had assumed it was when you make a transaction with Electrum that won't confirm for a while, then close Electrum, then in the meantime it's discarded from your node's mempool, then you open Electrum and it tries to request the transaction from your node which no longer has it.

Ive only used my node/wallet to receive transactions, not send any.

**Comment by lukechilds** [comment] 2021-02-20 09:56
The same scenario could occur if you receive a transaction into your node's mempool which notifies Electrum, Electrum keeps a copy, then your node purges that TX for some reason and Electrum later requests it again.

**Comment by ascisco** [comment] 2021-02-20 18:38
> The same scenario could occur if you receive a transaction into your node's mempool which notifies Electrum, Electrum keeps a copy, then your node purges that TX for some reason and Electrum later requests it again.

Do you know of any flags in the bitcoin.conf file I can set to help mitigate the problem?

**Comment by Kixunil** [comment] 2021-02-20 18:52
@ascisco try bumping mempool size

@lukechilds thanks for info! My progress is still slow sadly, too much other stuff to do. :(

**Comment by romanz** [comment] 2021-02-21 19:16
electrs is using `getrawmempool` and `getmempoolentry` RPCs to fetch mempool transactions.
Since transactions may leave the mempool (e.g. being confirmed, RBF) between subsequent RPCs - you would get the log above.
It's not an error, just a bit annoying artifact of the current operation mode of electrs.
How often does it happen?

**Comment by ascisco** [comment] 2021-02-22 07:55
It has only happened once so far, it has cleared up now and I am able to sync my wallet again.

I have since increased `-mempoolexpiry` and `-maxmempool` limits in hopes to mitigate the problem.

**Comment by fooedge2** [comment] 2021-05-02 12:06
I have tons of this messages in my log during each startup of electrs on my raspberry pi. The startup takes a very long time, usually 30 minutes or more. Electrum client won't sync during the startup time either and I think it is related to the "Transaction not in mempool" messages. I checked the transactions and they are in fact no longer in mempool but already mined in recent blocks.
Even if the time between shutdown and restart of electrs is only a 1-2 minutes, I get this behavior, so I think it somehow has an old version of the mempool, Is there any configuration possibility to avoid this scenario?

**Comment by romanz** [comment] 2021-05-02 19:19
Could you please try the latest `p2p` branch?
https://github.com/romanz/electrs/issues/308#issuecomment-806061229

It would require re-indexing the blockchain, but its index should be smaller (~30GB) and the mempool syncing should be faster and more robust.

**Comment by fooedge2** [comment] 2021-05-02 19:38
I will give it a try, thanks!

**Comment by fooedge2** [comment] 2021-05-03 19:40
Unfortunately that branch doesn't build on my rasperry pi (cargo build --locked --release).

It fails at 
 190/197: librocksdb-sys(build)

error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DZSTD=1" "-DNDEBUG=1" "-DOS_LINUX" "-DROCKSDB_PLATFORM_POSIX" "-DROCKSDB_LIB_IO_POSIX" "-o" "/home/pi/electrs/target/release/build/librocksdb-sys-7e0e2ec6b80a36e8/out/rocksdb/utilities/transactions/lock/range/range_tree/lib/locktree/lock_request.o" "-c" "rocksdb/utilities/transactions/lock/range/range_tree/lib/locktree/lock_request.cc" with args "c++" did not execute successfully (status code exit code: 1).

I get tons of warnings like this:
cargo:warning=    _M_realloc_insert(end(), __x);
cargo:warning=    ^~~~~~~~~~~~~~~~~
cargo:warning=/usr/include/c++/8/bits/stl_vector.h: In member function ‘virtual rocksdb::LockManager::PointLockStatus rocksdb::PointLockManager::GetPointLockStatus()’:
cargo:warning=/usr/include/c++/8/bits/stl_vector.h:1085:4: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<long long unsigned int*, std::vector<long long unsigned int> >’ changed in GCC 7.1
cargo:warning=    _M_realloc_insert(end(), __x);
cargo:warning=    ^~~~~~~~~~~~~~~~~

the only error I see is here, but I don't know if this caused the build to fail. 

cargo:warning=rocksdb/utilities/transactions/lock/range/range_tree/lib/locktree/../portability/toku_time.h:137:2: error: #error No timer implementation for this platform

**Comment by Kixunil** [comment] 2021-05-04 07:23
Your RPi is low on memory.

**Comment by fooedge2** [comment] 2021-05-04 19:21
I see, I'll try on a model with 8GB RAM then.

**Comment by romanz** [comment] 2021-05-08 07:09
Closing for now, please reopen if the issue persists.

**Closed by romanz** 2021-05-08 07:09 UTC
Labels: bug

**Comment by 2pac1** [comment] 2021-05-19 20:51
Seeing bunch of 
getmempoolentry RPC error: {"code":-5,"message":"Transaction not in mempool"}

messages after the reboot of the machine. Using Raspibolt setup.
Noticed this after updating.
CPU usage 100% and electrum cant seem to sync properly while this is going on.
I think it takes some time till it does it's thing.

**Comment by fooedge2** [comment] 2021-05-19 21:09
As there is someone else reporting this issue, I can also give some update. 
The p2p version fails also to build on an 8 GB model, the reason might be in rocksdb / toku_time, as there is no timer defined for 32 bit architecture, I don't know why the main branch builds without this problem though. 

`// Get the value of tokutime for right now.  We want this to be fast, so we expose the implementation as RDTSC.
static inline tokutime_t toku_time_now(void) {
#if defined(__x86_64__) || defined(__i386__)
    uint32_t lo, hi;
    __asm__ __volatile__ ("rdtsc" : "=a" (lo), "=d" (hi));
    return (uint64_t)hi << 32 | lo;
#elif defined (__aarch64__)
    uint64_t result;
    __asm __volatile__ ("mrs %[rt], cntvct_el0" : [rt] "=r" (result));
    return result;
#elif defined(__powerpc__)
    return __ppc_get_timebase();
#else
**#error No timer implementation for this platform**
#endif
}`

The `getmempoolentry RPC error: {"code":-5,"message":"Transaction not in mempool"}" `are not the only problems in the main branch, the database seems corrupt, not all transactions are found if I try to get a specific transaction by rpc call. I also tried to re-create the database from scratch but the problems appeared again, also on an 8 GB model, so it's not a memory issue as there is really plenty of memory left.

**Comment by 2pac1** [comment] 2021-05-20 07:00
After leaving it for a while, electrum syncs up instantly when started.
Will see if I reboot it again, does the CPU usage goes to 100% again and
again you can't sync.

Haven't noticed this before, but definitely something doen't look right.

Hashes that electrs log is spiting out regarding the mempool can't be found
in an rpc-btc explorer (404 page).

Would appreciate feedback.

**Comment by Kixunil** [comment] 2021-05-20 07:10
Can't look at the code right now, just two ideas to check: maybe hashes are reversed, maybe they are wtxids instead of txids.

**Comment by romanz** [comment] 2021-05-20 15:55
Please try the latest commit at the `p2p` branch, following https://github.com/romanz/electrs/issues/403.
