### ISSUE TITLE
Bug: Installation Problem in MacOS

### ISSUE THREAD

**Issue by anmode** [romanz/electrs#870] opened 2023-04-04 03:32 UTC
**Describe the bug**
```
 running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/table/plain/plain_table_reader.o" "-c" "rocksdb/table/plain/plain_table_reader.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/table/sst_file_reader.o" "-c" "rocksdb/table/sst_file_reader.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/table/sst_file_writer.o" "-c" "rocksdb/table/sst_file_writer.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/table/table_properties.o" "-c" "rocksdb/table/table_properties.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/table/two_level_iterator.o" "-c" "rocksdb/table/two_level_iterator.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/test_util/sync_point.o" "-c" "rocksdb/test_util/sync_point.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/test_util/sync_point_impl.o" "-c" "rocksdb/test_util/sync_point_impl.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/test_util/transaction_test_util.o" "-c" "rocksdb/test_util/transaction_test_util.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/tools/dump/db_dump_tool.o" "-c" "rocksdb/tools/dump/db_dump_tool.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/trace_replay/trace_replay.o" "-c" "rocksdb/trace_replay/trace_replay.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/trace_replay/block_cache_tracer.o" "-c" "rocksdb/trace_replay/block_cache_tracer.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/util/coding.o" "-c" "rocksdb/util/coding.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/util/compaction_job_stats_impl.o" "-c" "rocksdb/util/compaction_job_stats_impl.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/util/comparator.o" "-c" "rocksdb/util/comparator.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/util/compression_context_cache.o" "-c" "rocksdb/util/compression_context_cache.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/util/concurrent_task_limiter_impl.o" "-c" "rocksdb/util/concurrent_task_limiter_impl.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/util/crc32c.o" "-c" "rocksdb/util/crc32c.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/util/dynamic_bloom.o" "-c" "rocksdb/util/dynamic_bloom.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/util/hash.o" "-c" "rocksdb/util/hash.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/util/murmurhash.o" "-c" "rocksdb/util/murmurhash.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/util/random.o" "-c" "rocksdb/util/random.cc"
  cargo:warning=rocksdb/util/crc32c.cc:502:18: error: use of undeclared identifier 'isSSE42'
  cargo:warning=  has_fast_crc = isSSE42();
  cargo:warning=                 ^
  cargo:warning=rocksdb/util/crc32c.cc:1232:7: error: use of undeclared identifier 'isSSE42'
  cargo:warning=  if (isSSE42()) {
  cargo:warning=      ^
  cargo:warning=rocksdb/util/crc32c.cc:1233:9: error: use of undeclared identifier 'isPCLMULQDQ'
  cargo:warning=    if (isPCLMULQDQ()) {
  cargo:warning=        ^
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/util/rate_limiter.o" "-c" "rocksdb/util/rate_limiter.cc"
  exit status: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/util/slice.o" "-c" "rocksdb/util/slice.cc"
  cargo:warning=3 errors generated.
  exit status: 1
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/util/file_checksum_helper.o" "-c" "rocksdb/util/file_checksum_helper.cc"
  exit status: 0
  exit status: 0
  exit status: 0
  exit status: 0
  exit status: 0
  exit status: 0
  exit status: 0
  exit status: 0

  --- stderr


  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DZSTD=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL/release/build/electrs-librocksdb-sys-bcea5263fd08d5f5/out/rocksdb/util/crc32c.o" "-c" "rocksdb/util/crc32c.cc" with args "c++" did not execute successfully (status code exit status: 1).


error: failed to compile `electrs v0.9.13 (https://github.com/romanz/electrs#a2a5f7c1)`, intermediate artifacts can be found at `/var/folders/h8/383kjt3x1rjg7sff3j5cggqr0000gn/T/cargo-installya0RLL`
```

**Electrs version**
I did run this command `cargo install --git https://github.com/romanz/electrs --bin electrs`

**To Reproduce**
Just install with command `cargo install --git https://github.com/romanz/electrs --bin electrs
`

**Expected behavior**

**Configuration**

<details>
<summary>electrs.toml</summary>

```
type error message here
```

</details>

Environment variables: `ELECTRS_X=Y;...`
Arguments: `--foo`

**System running electrs**
 - Deployment method: manual (which guide did you follow?)/native OS package/Docker
 - OS name and version (name of distribution and version in case of Linux)

**Electrum client**
Client name (if not upstream desktop Electrum) and version:

**Additional context**

**Comment by romanz** [comment] 2023-04-06 19:10
Could you please try https://github.com/romanz/electrs/commits/bump-msrv branch?

**Comment by ssantos21** [comment] 2023-04-13 14:20
I have tested and confirmed that `cargo build --locked --release` does not work on the master branch on MacOS Intel Ventura and it works on the `bump-msrv` branch.

**Comment by romanz** [comment] 2023-04-13 19:01
Closing as a duplicate of #753.

**Closed by romanz** 2023-04-13 19:01 UTC
Labels: bug, build
