### ISSUE TITLE
Bug: Unable to index block 715209 "UnsupportedSegwitFlag(0)"

### ISSUE THREAD

**Issue by nymkappa** [romanz/electrs#665] opened 2022-01-15 14:59 UTC
I'm unable to index the block from a fresh install [0000000000000000000a4e783c4e20ddf64058009338e77b795d1077e582e0db](https://mempool.space/block/0000000000000000000a4e783c4e20ddf64058009338e77b795d1077e582e0db)

electrs v0.9.4
Bitcoin Core v22.0

I get the following error, can't find anything related online:

```
thread 'p2p_loop' panicked at 'invalid message: UnsupportedSegwitFlag(0)', src/p2p.rs:250:70
```

Full log
```
Starting electrs 0.9.4 on x86_64 linux with Config { network: Bitcoin, db_path: "/media/DATA/electrs/data/bitcoin", daemon_dir: "/home/joris/.bitcoin", daemon_auth: UserPass("mempool", "<sensitive>"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 127.0.0.1:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.4 (Electrum Rust Server)!", args: [] }
[2022-01-15T15:06:29.122Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
[2022-01-15T15:06:29.122Z INFO  electrs::server] serving Electrum RPC on 127.0.0.1:50001
[2022-01-15T15:06:29.122Z DEBUG tiny_http] Server listening on 127.0.0.1:4224
[2022-01-15T15:06:29.123Z DEBUG tiny_http] Running accept thread
[2022-01-15T15:06:29.214Z INFO  electrs::db] "/media/DATA/electrs/data/bitcoin": 621 SST files, 49.918163627 GB, 4.115181467 Grows
[2022-01-15T15:06:29.214Z DEBUG electrs::db] DB Some(Config { compacted: false, format: 0 })
[2022-01-15T15:06:30.807Z INFO  electrs::chain] loading 715200 headers, tip=0000000000000000000a8e6bac0398a0357532bce16340e8ba8431055d474e6c
[2022-01-15T15:06:32.747Z INFO  electrs::chain] chain updated: tip=0000000000000000000a8e6bac0398a0357532bce16340e8ba8431055d474e6c, height=715200
[2022-01-15T15:06:32.753Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2022-01-15T15:06:32.754Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2022-01-15T15:06:32.755Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2022-01-15T15:06:32.756Z DEBUG electrs::p2p] peer version: VersionMessage { version: 70016, services: ServiceFlags(1033), timestamp: 1642259187, receiver: Address {services: ServiceFlags(NONE), address: 0.0.0.0, port: 0}, sender: Address {services: ServiceFlags(NETWORK|WITNESS|NETWORK_LIMITED), address: 0.0.0.0, port: 0}, nonce: 5285437317951837697, user_agent: "/Satoshi:22.0.0/", start_height: 718823, relay: true }
[2022-01-15T15:06:32.758Z DEBUG electrs::p2p] got 2000 new headers
[2022-01-15T15:06:32.760Z INFO  electrs::index] indexing 2000 blocks: [715201..717200]
[2022-01-15T15:06:32.760Z DEBUG electrs::p2p] loading 10 blocks
thread 'p2p_loop' panicked at 'invalid message: UnsupportedSegwitFlag(0)', src/p2p.rs:250:70
stack backtrace:
   0:     0x55c9ee32474c - std::backtrace_rs::backtrace::libunwind::trace::h667de636fd16ec22
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55c9ee32474c - std::backtrace_rs::backtrace::trace_unsynchronized::hb6272615657d5744
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c9ee32474c - std::sys_common::backtrace::_print_fmt::h85b0a9a3797c535d
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55c9ee32474c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h33e1fc29f9141885
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55c9ee35c8ef - core::fmt::write::h3b0ec0911656cf8a
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/core/src/fmt/mod.rs:1094:17
   5:     0x55c9ee31fdc5 - std::io::Write::write_fmt::h015d8bf6ff8e54cc
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/io/mod.rs:1584:15
   6:     0x55c9ee3390fb - std::sys_common::backtrace::_print::hac8aff4fe690f889
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55c9ee3390fb - std::sys_common::backtrace::print::hcf7ce53748cfb74f
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55c9ee3390fb - std::panicking::default_hook::{{closure}}::h8e3df13515f3fd66
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/panicking.rs:208:50
   9:     0x55c9ee338cdf - std::panicking::default_hook::h468fd6be1a9a88b4
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/panicking.rs:225:9
  10:     0x55c9ee339603 - std::panicking::rust_panic_with_hook::h37bd253c0dc6b3b6
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/panicking.rs:591:17
  11:     0x55c9ee324c57 - std::panicking::begin_panic_handler::{{closure}}::hff24a561569e53dd
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/panicking.rs:497:13
  12:     0x55c9ee32488c - std::sys_common::backtrace::__rust_end_short_backtrace::h1e26e0dfac5e461e
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55c9ee339202 - rust_begin_unwind
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/panicking.rs:493:5
  14:     0x55c9edd39771 - core::panicking::panic_fmt::h134fc7184a83985e
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/core/src/panicking.rs:92:14
  15:     0x55c9edd39ae3 - core::result::unwrap_failed::hb0f1baf5c1816d17
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/core/src/result.rs:1355:5
  16:     0x55c9ede48f58 - prometheus::histogram::Histogram::observe_closure_duration::h8ba95767a1a4e044
  17:     0x55c9ede53817 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdc9888847a858894
  18:     0x55c9ede56a05 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h787cb060360fb7ab
  19:     0x55c9ee320848 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h140c34ae15ddced3
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/boxed.rs:1546:9
  20:     0x55c9ee320848 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9ea065b6c3e7ab5c
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/alloc/src/boxed.rs:1546:9
  21:     0x55c9ee320848 - std::sys::unix::thread::Thread::new::thread_start::h27ee83c9afd91f53
                               at /build/rustc-Nbf2Kl/rustc-1.53.0+dfsg1+llvm/library/std/src/sys/unix/thread.rs:71:17
  22:     0x7f52393cf609 - start_thread
  23:     0x7f52391a1293 - clone
  24:                0x0 - <unknown>
[2022-01-15T15:06:32.788Z DEBUG electrs::p2p] closing p2p_send thread: no more messages to send
[2022-01-15T15:06:32.788Z DEBUG electrs::p2p] closing p2p_recv thread: connection closed
[2022-01-15T15:06:32.789Z INFO  electrs::db] closing DB at /media/DATA/electrs/data/bitcoin
Error: electrs failed

Caused by:
    0: sync failed
    1: failed to get block 0000000000000000000a4e783c4e20ddf64058009338e77b795d1077e582e0db
    2: receiving on an empty and disconnected channel

```

**Comment by romanz** [comment] 2022-01-16 06:44
Many thanks for reporting this issue!
I failed to reproduce it on my machine :confused: 
Does it reproduce on yours?

**Comment by romanz** [comment] 2022-01-16 06:53
Could you please share your hardware & OS details?

**Comment by nymkappa** [comment] 2022-01-17 04:47
> Could you please share your hardware & OS details?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.2
Release:	20.2
Codename:	uma
```

I am running electrs on `/dev/sdb1`

```
$ sudo lshw -short
H/W path       Device          Class          Description
=========================================================
                               system         Inspiron 15 7000 Gaming (0798)
/0                             bus            0MK77P
/0/0                           memory         64KiB BIOS
/0/44                          memory         16GiB System Memory
/0/44/0                        memory         8GiB SODIMM DDR4 Synchronous 2400 MHz (0.4 ns)
/0/44/1                        memory         8GiB SODIMM DDR4 Synchronous 2400 MHz (0.4 ns)
/0/48                          memory         256KiB L1 cache
/0/49                          memory         1MiB L2 cache
/0/4a                          memory         6MiB L3 cache
/0/4b                          processor      Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
/0/100/1/0                     display        GP107M [GeForce GTX 1050 Ti Mobile]
/0/100/17                      storage        82801 Mobile SATA Controller [RAID mode]
/0/b           scsi0           storage        
/0/b/0.0.0     /dev/sda        disk           256GB SanDisk X400 M.2
/0/b/0.0.0/1   /dev/sda1       volume         511MiB Windows FAT volume
/0/b/0.0.0/2   /dev/sda2       volume         237GiB EXT4 volume
/0/c           scsi1           storage        
/0/c/0.0.0     /dev/sdb        disk           1TB CT1000MX500SSD1
/0/c/0.0.0/1   /dev/sdb1       volume         931GiB Windows NTFS volume
```

**Comment by romanz** [comment] 2022-01-17 08:15
Could you please run the following (and attach the resulting file)?
```
$ bitcoin-cli getblock 0000000000000000000a4e783c4e20ddf64058009338e77b795d1077e582e0db 0 > block.hex
```

**Comment by Kixunil** [comment] 2022-01-17 09:35
Is it possible this happens only on certain log level similarly to the case with overflow bug?

**Comment by romanz** [comment] 2022-01-17 11:13
@nymkappa Do you use `RUST_LOG` or `log_filters` setting for configuring logging verbosity?
If so, could you please share it?

**Comment by nymkappa** [comment] 2022-01-17 13:43
> Could you please run the following (and attach the resulting file)?
> 
> ```
> $ bitcoin-cli getblock 0000000000000000000a4e783c4e20ddf64058009338e77b795d1077e582e0db 0 > block.hex
> ```
Remove the `.txt` at the end of the file (github does not like .hex lol)
[block.hex.txt](https://github.com/romanz/electrs/files/7882188/block.hex.txt)

> @nymkappa Do you use `RUST_LOG` environment variable or `log_filters` setting for configuring logging verbosity? If so, could you please share it?

```
daemon_rpc_addr = "127.0.0.1:8332"
daemon_p2p_addr = "127.0.0.1:8333"
db_dir = "/media/DATA/electrs/data"
network = "bitcoin"
electrum_rpc_addr = "127.0.0.1:50001"
log_filters = "DEBUG" # Also tested with INFO
auth=....
```

**Comment by nymkappa** [comment] 2022-01-17 13:46
> @nymkappa Do you use `RUST_LOG` environment variable or `log_filters` setting for configuring logging verbosity? If so, could you please share it?

I tried with no `log_filters` at all. It fails with the same error.

**Comment by Kixunil** [comment] 2022-01-17 14:04
There's a shitload of zeroes at the end of your block and I don't have those zeroes. It' pretty much certainly corruption of your data. I recommend running bitcoind with the `-reindex` flag. Sadly, this will take about the same amount of time as resync from scratch.

**Comment by romanz** [comment] 2022-01-17 18:48
In addition, your block seems to be much shorter than the "canonical" one:
```
-rw-rw-r-- 1 roman roman 594229 Jan 17 15:45 b1.hex
-rw-rw-r-- 1 roman roman  27265 Jan 17 15:40 b2.hex
```
IIUC, the first one is the correct one (297114*2 + 1):
```
$ bitcoin-cli getblock 0000000000000000000a4e783c4e20ddf64058009338e77b795d1077e582e0db | jq .size
297114
```

**Comment by romanz** [comment] 2022-01-17 18:48
BTW, what does `bitcoin-cli getblock 0000000000000000000a4e783c4e20ddf64058009338e77b795d1077e582e0db` return?

**Comment by nymkappa** [comment] 2022-01-18 02:19
> bitcoin-cli getblock 0000000000000000000a4e783c4e20ddf64058009338e77b795d1077e582e0db 0 > block.hex

Seems like it's gone now that I started re-indexing???

```
$ bitcoin-cli getblock 0000000000000000000a4e783c4e20ddf64058009338e77b795d1077e582e0db
error code: -1
error message:
Block not found on disk
```

Previous (00000000000000000003839f187ea8357642d35c3afcada6c5a3ded89e704576) and next (0000000000000000000622b08ef42b50214b78f1fd3eee19e2aa560ae4cd0d8d) blocks are returning data.

**Comment by romanz** [comment] 2022-01-18 15:07
It seems that 0000000000000000000a4e783c4e20ddf64058009338e77b795d1077e582e0db was indeed corrupted.
Closing for now, please reopen if the issue persists after a reindex.

**Closed by romanz** 2022-01-18 15:07 UTC
Labels: bug, p2p

**Comment by nymkappa** [comment] 2022-01-19 01:07
I confirmed it worked fine again after re-syncing core + electrs. Sorry for the distraction and thank you very much for your support!
