### ISSUE TITLE
Electrs has a thread 'main' panicked error at launch

### ISSUE THREAD

**Issue by roshan-dias** [romanz/electrs#448] opened 2021-07-28 23:04 UTC
I configured electrs following the stadicus guide and have the following error on launch:

2021-07-29T00:00:07.422+01:00 - DEBUG - Server listening on 127.0.0.1:4224
thread 'main' panicked at 'attempted to leave type `lru::LruEntry<bitcoin_hashes::sha256d::Hash, (std::vec::Vec<bitcoin_hashes::sha256d::Hash>, usize)>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2021-07-29T00:00:07.423+01:00 - DEBUG - Running accept thread

I've tried editing the electrs.conf file to include the Rust Backtrace variable but this didn't change anything.

I've also looked at the bitcoin.conf file to make sure passwords and usernames are correct, I have also turned off ufw in case that was causing any issues.

**Expected behavior**
Expected Electrs to start syncing but it crashed on launch

**Comment by Kixunil** [comment] 2021-07-29 07:06
You have to set `RUST_BACKTRACE=1` as **environment variable**. E.g. type `export RUST_BACKTRACE=1` in the shell before starting `electrs` to provide backtrace - please do.

Also, please fill the bug report template so that we know which `electrs` and platform do you use:

**System running electrs**
 - Deployment method: manual/native OS package/Docker
 - OS name and version (name of distribution and version in case of Linux)


Also, in your case, if you compiled `electrs` yourself, please tell us your Rust version (`cargo --version` and `rustc --version`), whether you compiled with `--locked` and which `electrs` version did you compile.

**Comment by roshan-dias** [comment] 2021-07-29 21:58
Thank you Kixunil, your reply was really helpful. I'm not entirely sure how to fill in a bug report template, but I will give it a go.

#### Issue description
Electrs won't run and index the blockchain. It reports back errors when I run it.


#### Steps to reproduce the issue
I am running Electrs using this command: (sorry I don't know how to format command line text)
electrs --conf /mnt/ext/electrs/electrs.conf

#### What's the expected result?
After running the above command I am expecting electrs to index the blockchain and run
-


#### What's the actual result?
Config { log: StdErrLog { verbosity: Trace, quiet: false, timestamp: Millisecond, modules: [], writer: "stderr", color_choice: Auto }, network_type: bitcoin, db_path: "/mnt/ext/electrs/db/mainnet", daemon_dir: "/mnt/ext/bitcoin", daemon_rpc_addr: 127.0.0.1:8332, electrum_rpc_addr: 127.0.0.1:50001, monitoring_addr: 127.0.0.1:4224, jsonrpc_import: false, index_batch_size: 100, bulk_index_threads: 4, tx_cache_size: 10485760, txid_limit: 1000, server_banner: "Welcome to electrs 0.8.2 (Electrum Rust Server)!", blocktxids_cache_size: 10485760 }
2021-07-29T22:47:46.848+01:00 - DEBUG - Server listening on 127.0.0.1:4224
thread 'main' panicked at 'attempted to leave type `lru::LruEntry<bitcoin_hashes::sha256d::Hash, (std::vec::Vec<bitcoin_hashes::sha256d::Hash>, usize)>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658:9
stack backtrace:
2021-07-29T22:47:46.850+01:00 - DEBUG - Running accept thread
   0:   0x611644 - std::backtrace_rs::backtrace::libunwind::trace::he36f6f7ccfea7cc4
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:   0x611644 - std::backtrace_rs::backtrace::trace_unsynchronized::hac123ddf4c89e0de
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:   0x611644 - std::sys_common::backtrace::_print_fmt::h1253d384aeb41e66
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:   0x611644 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9bfa0f3e73c8a71c
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:   0x4c4c78 - core::fmt::write::h318bd4afa765e968
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:   0x610ca0 - std::io::Write::write_fmt::h978d52350c75a346
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:   0x6103d4 - std::sys_common::backtrace::_print::h753a497d2f71e1c8
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:   0x6103d4 - std::sys_common::backtrace::print::h537e6bf5eccb83f4
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:   0x6103d4 - std::panicking::default_hook::{{closure}}::h9198cdd1b3a29eee
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:   0x6103d4 - std::panicking::default_hook::h358b6f3c3116f66c
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:   0x6103d4 - std::panicking::rust_panic_with_hook::h5f8602b3dd6084d8
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:   0x62e088 - std::panicking::begin_panic_handler::{{closure}}::h4d95fbdac6260e23
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:   0x62e04c - std::sys_common::backtrace::__rust_end_short_backtrace::h85c591e02fe73d03
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:   0x62e004 - rust_begin_unwind
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:   0x4c2a24 - core::panicking::panic_fmt::hf49053651214abed
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:   0x4c2824 - core::panicking::panic::h35c6dfebfb49d6a8
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
  16:   0x4fc0e8 - electrs::cache::BlockTxIDsCache::new::h6a3685e841cab4dc
  17:   0x4a838c - electrs::main::h2a80b5c7be5b50d8
  18:   0x5521b4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h77fdede6a2066378
  19:   0x4afd90 - main
  20: 0xb6cce718 - __libc_start_main

-


#### Additional details / screenshot
cargo 1.48.0 (65cbdd2dc 2020-10-14)
rustc 1.48.0 (7eac88abb 2020-11-16)

I compiled Electrs and used version 0.8.2

Running on a Raspberry pi 4 Buster

I think that is everything, hopefully I have presented the information correctly? Sorry for being so rubbish at this. I haven't really used linux before and I have managed to get bitcoind, LND, RTL running using Stadicus guide but it has taken me three weeks of problem solving to get this far!

- ![Screenshot]()

**Comment by Kixunil** [comment] 2021-07-29 22:11
That looks useful! I can't look at it properly right now but at least we have something.

FYI to format a big block of command line output you can use triple backticks like this:

\`\`\`
Put text here
\`\`\`

**Comment by Kixunil** [comment] 2021-07-30 05:18
Figured out the reason why this happens 0.8.2 is using ancient LRU, which uses [unsound `uninitialized`](https://github.com/jeromefroe/lru-rs/blob/12a4b374088a66de7fc642d7938e40688fe70eec/src/lib.rs#L216) 0.8.10 has up-to-date version of LRU.

@roshan-dias please try compiling newer version. You can switch it by running these command:

```
git fetch origin
git checkout v0.8.10
cargo build --locked --release
```

**Comment by roshan-dias** [comment] 2021-08-01 19:03
@Kixunil Thank you for your post. I am still very noob at Linux. I've tried to fetch the updated files but I can't even do that... sorry do you have one more point for me? I tried

```
git fetch origin https://github.com/romanz/electrs
```

Sorry this is really embarrassing I can't even follow a basic instruction. I found a script on github to install electrs on raspberry pi but I would rather try and improve my knowledge as I go along through setting this up.

**Comment by Kixunil** [comment] 2021-08-02 09:06
Did you try without URL? It should work if you're inside `electrs` directory. (`cd /home/admin/rust/electrs` according to RaspiBolt guide) If you did, what did it print out?

**Comment by roshan-dias** [comment] 2021-08-02 15:53
Thank you, I just tried in the electrs directory and there was no output after

```
git fetch origin
```
and this error after
```
git checkout v0.8.10
```
![image](https://user-images.githubusercontent.com/53953898/127889260-23cb9d41-5b9c-4c20-a50c-d298a5a04f6f.png)

**Comment by roshan-dias** [comment] 2021-08-02 16:02
The output is 

https://github.com/romanz/electrs.git

**Comment by Kixunil** [comment] 2021-08-02 16:16
I think this should help:

```
git fetch --tags
git checkout v0.8.10
```

**Comment by roshan-dias** [comment] 2021-08-02 20:31
Thank you again. I've updated to v0.8.10 and I'm still getting the same error as before. I've checked my electrs.conf file and have the correct password. Have you got any further suggestions of what the issue maybe?

```
bitcoin@raspberrypi:~ $ electrs --conf /mnt/ext/electrs/electrs.conf
Config { log: StdErrLog { verbosity: Trace, quiet: false, timestamp: Millisecond, modules: [], writer: "stderr", color_choice: Auto }, network_type: bitcoin, db_path: "/mnt/ext/electrs/db/mainnet", daemon_dir: "/mnt/ext/bitcoin", daemon_rpc_addr: 127.0.0.1:8332, electrum_rpc_addr: 127.0.0.1:50001, monitoring_addr: 127.0.0.1:4224, jsonrpc_import: false, index_batch_size: 100, bulk_index_threads: 4, tx_cache_size: 10485760, txid_limit: 1000, server_banner: "Welcome to electrs 0.8.2 (Electrum Rust Server)!", blocktxids_cache_size: 10485760 }
2021-08-02T21:26:26.283+01:00 - DEBUG - Server listening on 127.0.0.1:4224
thread 'main' panicked at 'attempted to leave type `lru::LruEntry<bitcoin_hashes::sha256d::Hash, (std::vec::Vec<bitcoin_hashes::sha256d::Hash>, usize)>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658:9
stack backtrace:
2021-08-02T21:26:26.287+01:00 - DEBUG - Running accept thread
   0:   0x601644 - std::backtrace_rs::backtrace::libunwind::trace::he36f6f7ccfea7cc4
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:   0x601644 - std::backtrace_rs::backtrace::trace_unsynchronized::hac123ddf4c89e0de
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:   0x601644 - std::sys_common::backtrace::_print_fmt::h1253d384aeb41e66
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:   0x601644 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9bfa0f3e73c8a71c
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:   0x4b4c78 - core::fmt::write::h318bd4afa765e968
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:   0x600ca0 - std::io::Write::write_fmt::h978d52350c75a346
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:   0x6003d4 - std::sys_common::backtrace::_print::h753a497d2f71e1c8
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:   0x6003d4 - std::sys_common::backtrace::print::h537e6bf5eccb83f4
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:   0x6003d4 - std::panicking::default_hook::{{closure}}::h9198cdd1b3a29eee
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:   0x6003d4 - std::panicking::default_hook::h358b6f3c3116f66c
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:   0x6003d4 - std::panicking::rust_panic_with_hook::h5f8602b3dd6084d8
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:   0x61e088 - std::panicking::begin_panic_handler::{{closure}}::h4d95fbdac6260e23
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:   0x61e04c - std::sys_common::backtrace::__rust_end_short_backtrace::h85c591e02fe73d03
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:   0x61e004 - rust_begin_unwind
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:   0x4b2a24 - core::panicking::panic_fmt::hf49053651214abed
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:   0x4b2824 - core::panicking::panic::h35c6dfebfb49d6a8
                       at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
  16:   0x4ec0e8 - electrs::cache::BlockTxIDsCache::new::h6a3685e841cab4dc
  17:   0x49838c - electrs::main::h2a80b5c7be5b50d8
  18:   0x5421b4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h77fdede6a2066378
  19:   0x49fd90 - main
  20: 0xb6ca4718 - __libc_start_main
```

My conf file is

```
# RaspiBolt: electrs configuration
# /mnt/ext/electrs/electrs.conf

# RPC user / password
cookie = "raspibolt:****"

# Bitcoin Core settings
network = "bitcoin"
daemon_dir= "/mnt/ext/bitcoin"
daemon_rpc_addr = "127.0.0.1:8332"

# Electrs settings
electrum_rpc_addr = "127.0.0.1:50001"
db_dir = "/mnt/ext/electrs/db"
txid_limit = 1000

# Logging
verbose = 4
timestamp = true
rust_backtrace = 1
```

**Comment by roshan-dias** [comment] 2021-08-02 20:44
Just to add I have checked my ports are open (and turned off the firewall just in case) and I have also checked that the bitcoin user has the correct file rights for /mnt/ext which was causing me issues with Bitcoind.

**Comment by Kixunil** [comment] 2021-08-02 20:46
Did you rebuild (`cargo build --locked --release`) and re-copied (`sudo cp ./target/release/electrs /usr/local/bin/`) the new version?

Note also that `cookie` option is deprecated and will be removed as explained in https://github.com/Stadicus/RaspiBolt/issues/747 It will work for now so let's focus on getting it running first and fix it then.

**Comment by roshan-dias** [comment] 2021-08-02 21:37
Thank you, I didn't realise I needed to copy the file into that directory. I do now! Sorry I'm very slow at Linux took me all that time to work out where to find the file, I was trying to copy a symbolic link a I created and made a right mess of it.

That seems to have sorted that issue but now I have the following error when running electrs:

```
2021-08-02T22:21:29.504+01:00 - WARN - reconnecting to bitcoind: no reply from daemon
2021-08-02T22:22:02.784+01:00 - WARN - reconnecting to bitcoind: no reply from daemon
2021-08-02T22:22:36.064+01:00 - WARN - reconnecting to bitcoind: no reply from daemon
```

and when I check the logs from bitcoind I have this error
```

2021-08-02T21:21:32Z ThreadRPCServer incorrect password attempt from 127.0.0.1:57962
2021-08-02T21:22:05Z ThreadRPCServer incorrect password attempt from 127.0.0.1:57966
2021-08-02T21:22:39Z ThreadRPCServer incorrect password attempt from 127.0.0.1:57968
2021-08-02T21:22:42Z Socks5() connect to 78.255.205.230:8333 failed: general failure
```

The password in bitcoin.conf and electrs.conf are the same but you mentioned that the cookie option will be deprecated. Am I missing something from my electrs.conf file? 

I'm currently trying to find my bitcoin cookie file, I've checked var/run/bitcoind but it isn't in there and I have checked mnt/ext/bitcoin/ which is where my blockchain is stored and I cannot find it in there either as I think that may be the issue perhaps?

**Comment by roshan-dias** [comment] 2021-08-02 21:39
I've found the template electrs.conf file 

```
# File where bitcoind stores the cookie, usually file .cookie in its datadir
cookie_file = "/var/run/bitcoin-mainnet/cookie"
```
So I guess I need to add this in and remove the reference to the cookie username and password once I have found my cookie.

**Comment by Kixunil** [comment] 2021-08-03 06:28
> I didn't realise I needed to copy the file into that directory.

No problem something similar happened to me way too many times. :laughing: 

The cookie file is hidden by default, you can check it by running `ls -A /mnt/ext/bitcoin/` - should show up as `.cookie` (files beginning with dot are hidden).

If it's not there perhaps you need to set `rpccookiefile=/mnt/ext/bitcoin/`

**Comment by romanz** [comment] 2021-09-18 17:37
@roshan-dias Could you please try to reproduce this issue on the latest `v0.9.0-rc1` release?

**Comment by flounderella** [comment] 2021-09-18 23:09
v0.9.0-rc1 upgrade not doing so well. The process keeps panic-exiting

Sep 19 00:08:54 raspibolt electrs[17069]: thread '<unnamed>' panicked at 'slice index starts at 5 but ends at 4', /home/admin/.cargo/registry/src/github.com-1285ae84e5963aae/bitcoin-0.27.0/src/blockdata/script.rs:531:32
Sep 19 00:08:54 raspibolt electrs[17069]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Sep 19 00:08:54 raspibolt electrs[17069]: [2021-09-18T23:08:54.978Z INFO  electrs::db] closing DB at /mnt/ext/electrs/db/bitcoin
Sep 19 00:08:54 raspibolt systemd[1]: electrs.service: Main process exited, code=exited, status=101/n/a
Sep 19 00:08:54 raspibolt systemd[1]: electrs.service: Failed with result 'exit-code'.

**Comment by romanz** [comment] 2021-09-19 06:40
@flounderella Seems similar to https://github.com/romanz/electrs/issues/490 - let's continue the discussion there.

**Comment by romanz** [comment] 2021-09-23 15:21
Closing for now, please reopen if still relevant.

**Closed by romanz** 2021-09-23 15:21 UTC
Labels: bug
